### ISSUE TITLE
Don't see any data in DB?

### ISSUE THREAD

**Issue by SebastianBO** [sgr-ksmt/FireTodo#1]
I understand it's anonymous login, is this why the db is not getting synced up?

**Comment by sgr-ksmt** [comment]
If you setup project(Xcode, Firebase) correctly, the task data will be written to Cloud Firestore followings:

<img width="1278" alt="Screen Shot 2019-10-01 at 0 58 31" src="https://user-images.githubusercontent.com/9350581/65895545-9bf4b680-e3e6-11e9-9471-4afda7b3877a.png">

For example, the task document path will be `users/{uid}/tasks/{task_id}` because I want to manage tasks for each user.
Therefore, the task document will be written as Sub Collection of user document after signed in with anonymous method.

**Comment by SebastianBO** [comment]
Thank you for the response
